project:
  type: manuscript

notebook-links: global

manuscript:
  article: index.qmd
  notebooks:
    - notebook: appendix/gbif.ipynb
      title: Supp. Mat. XX - GBIF data
    - notebook: appendix/consensus.ipynb
      title: Supp. Mat. XX - Landcover consensus
    - notebook: appendix/sdm.ipynb
      title: Supp. Mat. YY - Species distribution model
    - notebook: appendix/virtualspecies.ipynb
      title: Supp. Mat. ZZ - Creating virtual species

lang: en-CA

format:
  html:
    comments:
      hypothesis: true
  docx: default
  preprint-pdf:
    csl: https://www.zotero.org/styles/methods-in-ecology-and-evolution
    mainfont: TeX Gyre Pagella Math
    monofont: TeX Gyre Termes
    sansfont: TeX Gyre Heros 
    formatting:
      draft-format: false
      author-sheet: false

execute:
  freeze: true



