project:
  type: manuscript

notebook-links: global

manuscript:
  article: index.qmd
  notebooks:
    - notebook: appendix/gbif.ipynb
      title: Supp. Mat. XX - GBIF data
    - notebook: appendix/consensus.ipynb
      title: Supp. Mat. XX - Landcover consensus
    - notebook: appendix/sdm.ipynb
      title: Supp. Mat. YY - Species distribution model
    - notebook: appendix/virtualspecies.ipynb
      title: Supp. Mat. ZZ - Creating virtual species

lang: en-CA

format:
  html:
    comments:
      hypothesis: true
  docx: default
  typst:
    toc: false
    mainfont: "TeX Gyre Pagella"
    fontsize: 10pt
    citeproc: true
    bibliographystyle: https://www.zotero.org/styles/methods-in-ecology-and-evolution
    papersize: us-letter
    margin:
      x: 1.8cm
      y: 2cm
    columns: 2
    include-before-body:
      - text: |
          #show heading: set text(navy)

execute:
  freeze: true



