project:
  type: manuscript

notebook-links: global

manuscript:
  article: index.qmd
  notebooks:
    - notebook: appendix/1-gbif.ipynb
      title: Supp. Mat. 1 - GBIF data
    - notebook: appendix/2-consensus.ipynb
      title: Supp. Mat. 2 - Landcover consensus
    - notebook: appendix/3-sdm.ipynb
      title: Supp. Mat. 3 - Species distribution model
    - notebook: appendix/4-virtualspecies.ipynb
      title: Supp. Mat. 4 - Creating virtual species

lang: en-CA

format:
  html:
    comments:
      hypothesis: true
  docx: default
  cerg-typst: default
execute:
  freeze: true