project:
  type: manuscript

notebook-links: global

manuscript:
  article: index.qmd
  notebooks:
    - notebook: appendix/consensus.ipynb
      title: Supp. Mat. 1 - Landcover consensus
    - notebook: appendix/gbif.ipynb
      title: Supp. Mat. 2 - GBIF data
    - notebook: appendix/sdm.ipynb
      title: Supp. Mat. 3 - Species distribution model
    - notebook: appendix/virtualspecies.ipynb
      title: Supp. Mat. 4 - Creating virtual species

lang: en-CA

format:
  html:
    comments:
      hypothesis: true
  docx: default
  typst:
    toc: false
    fontsize: 10pt
    papersize: us-letter
    bibliography: references.bib
    bibliographystyle: apa
    margin:
      x: 1.8cm
      y: 2cm
    columns: 2
    include-before-body:
      - text: |
          #set par(leading: 0.5em)
          #show heading.where(level: 1): set text(rgb("#114f54"))
          #show heading.where(level: 2): set text(rgb("#2e5385"))
          #show heading.where(level: 1): it => block(width: 100%)[
            #block(it.body)
          ]
          #show heading.where(level: 2): it => text(
            style: "italic",
            weight: "regular",
            size: 10pt,
            it.body + [: ]
          )

execute:
  freeze: true